---

# docker compose up --build

version: '3.9'

services:
  backend:
    build: ./backend
    container_name: backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:7.2.4-alpine
    restart: always

